<?php
/*
 * Copyright (C) 2013-2021 Combodo SARL
 * This file is part of iTop.
 * iTop is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * iTop is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 */

namespace Combodo\iTop\Monitoring\Test\MetricReader;

use Combodo\iTop\Monitoring\MetricReader\MetricReaderFactory;
use Combodo\iTop\Monitoring\MetricReader\OqlConfReader;
use Combodo\iTop\Monitoring\MetricReader\OqlCountReader;
use Combodo\iTop\Monitoring\MetricReader\OqlGroupByReader;

class MetricReaderFactoryTest extends \PHPUnit\Framework\TestCase
{
    public function setUp()
    {
        require_once '/home/nono/PhpstormProjects/iTop/approot.inc.php';
        parent::setUp(); // TODO: Change the autogenerated stub

        require_once(APPROOT . 'env-production/combodo-monitoring/vendor/autoload.php');
    }

    /**
     * @dataProvider GetReaderProvider
     */
    public function testGetReader($aMetric, $sExpectedClass)
    {
        $oMetricReaderFactory = new MetricReaderFactory();
        $result = $oMetricReaderFactory->GetReader('foo', $aMetric);
        $this->assertInstanceOf($sExpectedClass, $result);
    }

    public function GetReaderProvider()
    {
        return [
            'count' => [
                'aMetric' => [
                    'oql_count' => [ ],
                ],
                'sExpectedClass' => OqlCountReader::class,
            ],
            'group by' => [
                'aMetric' => [
                    'oql_groupby' => [ ],
                ],
                'sExpectedClass' => OqlGroupByReader::class,
            ],
            'conf' => [
                'aMetric' => [
                    'conf' => [ ],
                ],
                'sExpectedClass' => OqlConfReader::class,
            ],
        ];
    }
}